# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: db06443107208952e5117a22e3672265ecd2a6fb0c4b41153fa1f6e845ed12ba1a5ad4a1b347707cbfe0528d18541ef22c4f857ec52a4968e3ef083da99718bc

test:
  secret_key_base: 0f22c33a47b649a90fe75800f34bc0008ae52dcff465fab250151772c27698f8c2a54ce7ad43f0a7fb8716292ab87dde84f1e20e150e5c5efc9dc719a2ed584d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
